# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KosdaqShort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('short', models.IntegerField(blank=True, null=True)),
                ('short_proportion', models.FloatField(blank=True, null=True)),
                ('short_total_price', models.IntegerField(blank=True, null=True)),
                ('short_avg_price', models.IntegerField(blank=True, null=True)),
                ('short_zsclae', models.FloatField(blank=True, null=True)),
                ('short_section', models.IntegerField(blank=True, null=True)),
                ('tp_5d_mean', models.FloatField(blank=True, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kd_short', to='stockapi.Ticker')),
            ],
        ),
        migrations.CreateModel(
            name='KospiShort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('short', models.IntegerField(blank=True, null=True)),
                ('short_proportion', models.FloatField(blank=True, null=True)),
                ('short_total_price', models.IntegerField(blank=True, null=True)),
                ('short_avg_price', models.IntegerField(blank=True, null=True)),
                ('short_zsclae', models.FloatField(blank=True, null=True)),
                ('short_section', models.IntegerField(blank=True, null=True)),
                ('tp_5d_mean', models.FloatField(blank=True, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kp_short', to='stockapi.Ticker')),
            ],
        ),
    ]
