from django.conf.urls import url

from stockapi.views import (
    BenchmarkAPIView,
    TickerAPIView,
    KospiOHLCVAPIView,
    KosdaqOHLCVAPIView,
    RecentKospiOHLCVAPIView,
    RecentKosdaqOHLCVAPIView,
    InfoAPIView,
    SpecsAPIView,
    FinancialAPIView,
    FinancialRatioAPIView,
    QuarterFinancialAPIView,
    KospiBuyAPIView,
    KosdaqBuyAPIView,
    KospiSellAPIView,
    KosdaqSellAPIView,
    KospiNetAPIView,
    KosdaqNetAPIView,
    KospiShortAPIView,
    KosdaqShortAPIView,
)

urlpatterns = [
    url(r'^bm/$', BenchmarkAPIView.as_view(), name='bm'),
    url(r'^ticker/$', TickerAPIView.as_view(), name='ticker'),
    url(r'^kp-ohlcv/$', KospiOHLCVAPIView.as_view(), name='kp-ohlcv'),
    url(r'^kd-ohlcv/$', KosdaqOHLCVAPIView.as_view(), name='kd-ohlcv'),
    url(r'^recent-kp/$', RecentKospiOHLCVAPIView.as_view(), name='recent-kp-ohlcv'),
    url(r'^recent-kd/$', RecentKosdaqOHLCVAPIView.as_view(), name='recent-kd-ohlcv'),
    url(r'^info/$', InfoAPIView.as_view(), name='info'),
    url(r'^specs/$', SpecsAPIView.as_view(), name='specs'),
    url(r'^financial/$', FinancialAPIView.as_view(), name='financial'),
    url(r'^financial-ratio/$', FinancialRatioAPIView.as_view(), name='financial-ratio'),
    url(r'^quarter-financial/$', QuarterFinancialAPIView.as_view(), name='quarter-financial'),
    url(r'^kp-buy/$', KospiBuyAPIView.as_view(), name='kp-buy'),
    url(r'^kd-buy/$', KosdaqBuyAPIView.as_view(), name='kd-buy'),
    url(r'^kp-sell/$', KospiSellAPIView.as_view(), name='kp-sell'),
    url(r'^kd-sell/$', KosdaqSellAPIView.as_view(), name='kd-sell'),
    url(r'^kp-net/$', KospiNetAPIView.as_view(), name='kp-net'),
    url(r'^kd-net/$', KosdaqNetAPIView.as_view(), name='kd-net'),
    url(r'^kp-short/$', KospiShortAPIView.as_view(), name='kp-short'),
    url(r'^kd-short/$', KosdaqShortAPIView.as_view(), name='kd-short'),
]
