# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCalcData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('ind_tp', models.FloatField(blank=True, null=True)),
                ('for_tp', models.FloatField(blank=True, null=True)),
                ('ins_tp', models.FloatField(blank=True, null=True)),
                ('cor_tp', models.FloatField(blank=True, null=True)),
                ('ind_buy_cumsum', models.BigIntegerField(blank=True, null=True)),
                ('for_buy_cumsum', models.BigIntegerField(blank=True, null=True)),
                ('ins_buy_cumsum', models.BigIntegerField(blank=True, null=True)),
                ('cor_buy_cumsum', models.BigIntegerField(blank=True, null=True)),
                ('ind_tp_buy_cumsum', models.BigIntegerField(blank=True, null=True)),
                ('for_tp_buy_cumsum', models.BigIntegerField(blank=True, null=True)),
                ('ins_tp_buy_cumsum', models.BigIntegerField(blank=True, null=True)),
                ('cor_tp_buy_cumsum', models.BigIntegerField(blank=True, null=True)),
                ('ind_apps', models.FloatField(blank=True, null=True)),
                ('for_apps', models.FloatField(blank=True, null=True)),
                ('ins_apps', models.FloatField(blank=True, null=True)),
                ('cor_apps', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('ind_possession', models.BigIntegerField(blank=True, null=True)),
                ('for_possession', models.BigIntegerField(blank=True, null=True)),
                ('ins_possession', models.BigIntegerField(blank=True, null=True)),
                ('cor_possession', models.BigIntegerField(blank=True, null=True)),
                ('tru_possession', models.BigIntegerField(blank=True, null=True)),
                ('pen_possession', models.BigIntegerField(blank=True, null=True)),
                ('circulate_stock', models.BigIntegerField(blank=True, null=True)),
                ('ins_purity', models.FloatField(blank=True, null=True)),
                ('ind_height', models.FloatField(blank=True, null=True)),
                ('for_height', models.FloatField(blank=True, null=True)),
                ('ins_height', models.FloatField(blank=True, null=True)),
                ('cor_height', models.FloatField(blank=True, null=True)),
                ('ind_proportion', models.FloatField(blank=True, null=True)),
                ('for_proportion', models.FloatField(blank=True, null=True)),
                ('ins_proportion', models.FloatField(blank=True, null=True)),
                ('cor_proportion', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefacoTicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=50)),
                ('market_type', models.CharField(max_length=10)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RankData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('lead_agent', models.CharField(blank=True, max_length=20, null=True)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=40, null=True)),
                ('rank_change', models.IntegerField(blank=True, null=True)),
                ('sign', models.CharField(blank=True, max_length=10, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_data', to='defacto.DefacoTicker')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('absolute_score', models.FloatField(blank=True, null=True)),
                ('relative_score', models.FloatField(blank=True, null=True)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('score_rank', models.IntegerField(blank=True, null=True)),
                ('rank_change', models.IntegerField(blank=True, null=True)),
                ('score_change', models.FloatField(blank=True, null=True)),
                ('lead_agent', models.CharField(blank=True, max_length=20, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_data', to='defacto.DefacoTicker')),
            ],
        ),
        migrations.AddField(
            model_name='agentdata',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_data', to='defacto.DefacoTicker'),
        ),
        migrations.AddField(
            model_name='agentcalcdata',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_calc_data', to='defacto.DefacoTicker'),
        ),
    ]
