# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-01 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stockapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCalcData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('ind_tp', models.FloatField(blank=True, null=True)),
                ('for_tp', models.FloatField(blank=True, null=True)),
                ('ins_tp', models.FloatField(blank=True, null=True)),
                ('cor_tp', models.FloatField(blank=True, null=True)),
                ('ind_buy_cumsum', models.BigIntegerField(blank=True, null=True)),
                ('for_buy_cumsum', models.BigIntegerField(blank=True, null=True)),
                ('ins_buy_cumsum', models.BigIntegerField(blank=True, null=True)),
                ('cor_buy_cumsum', models.BigIntegerField(blank=True, null=True)),
                ('ind_tp_buy_cumsum', models.BigIntegerField(blank=True, null=True)),
                ('for_tp_buy_cumsum', models.BigIntegerField(blank=True, null=True)),
                ('ins_tp_buy_cumsum', models.BigIntegerField(blank=True, null=True)),
                ('cor_tp_buy_cumsum', models.BigIntegerField(blank=True, null=True)),
                ('ind_apps', models.FloatField(blank=True, null=True)),
                ('for_apps', models.FloatField(blank=True, null=True)),
                ('ins_apps', models.FloatField(blank=True, null=True)),
                ('cor_apps', models.FloatField(blank=True, null=True)),
                ('lead_agent', models.CharField(blank=True, max_length=20, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_calc_data', to='stockapi.Ticker')),
            ],
        ),
        migrations.CreateModel(
            name='AgentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('ind_possession', models.BigIntegerField(blank=True, null=True)),
                ('for_possession', models.BigIntegerField(blank=True, null=True)),
                ('ins_possession', models.BigIntegerField(blank=True, null=True)),
                ('cor_possession', models.BigIntegerField(blank=True, null=True)),
                ('tru_possession', models.BigIntegerField(blank=True, null=True)),
                ('pen_possession', models.BigIntegerField(blank=True, null=True)),
                ('circulate_stock', models.BigIntegerField(blank=True, null=True)),
                ('ins_purity', models.FloatField(blank=True, null=True)),
                ('ind_height', models.FloatField(blank=True, null=True)),
                ('for_height', models.FloatField(blank=True, null=True)),
                ('ins_height', models.FloatField(blank=True, null=True)),
                ('cor_height', models.FloatField(blank=True, null=True)),
                ('ind_proportion', models.FloatField(blank=True, null=True)),
                ('for_proportion', models.FloatField(blank=True, null=True)),
                ('ins_proportion', models.FloatField(blank=True, null=True)),
                ('cor_proportion', models.FloatField(blank=True, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_data', to='stockapi.Ticker')),
            ],
        ),
        migrations.CreateModel(
            name='DefactoReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=6)),
                ('ind_tv', models.FloatField(blank=True, null=True)),
                ('for_tv', models.FloatField(blank=True, null=True)),
                ('ins_tv', models.FloatField(blank=True, null=True)),
                ('cor_tv', models.FloatField(blank=True, null=True)),
                ('ind_coef', models.FloatField(blank=True, null=True)),
                ('for_coef', models.FloatField(blank=True, null=True)),
                ('ins_coef', models.FloatField(blank=True, null=True)),
                ('cor_coef', models.FloatField(blank=True, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defacto_reg', to='stockapi.Ticker')),
            ],
        ),
        migrations.CreateModel(
            name='RankData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('lead_agent', models.CharField(blank=True, max_length=20, null=True)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=40, null=True)),
                ('rank_change', models.IntegerField(blank=True, null=True)),
                ('sign', models.CharField(blank=True, max_length=10, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_data', to='stockapi.Ticker')),
            ],
        ),
        migrations.CreateModel(
            name='RelativeCalc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=6)),
                ('cp_vol', models.FloatField(blank=True, null=True)),
                ('cp_vol_section', models.IntegerField(blank=True, null=True)),
                ('ins_tp_diff', models.FloatField(blank=True)),
                ('for_tp_diff', models.FloatField(blank=True)),
                ('ins_price_inc', models.FloatField(blank=True)),
                ('for_price_inc', models.FloatField(blank=True)),
                ('cp_ind', models.FloatField(blank=True, null=True)),
                ('cp_for', models.FloatField(blank=True, null=True)),
                ('cp_ins', models.FloatField(blank=True, null=True)),
                ('cp_cor', models.FloatField(blank=True, null=True)),
                ('cp_ind_section', models.IntegerField(blank=True, null=True)),
                ('cp_for_section', models.IntegerField(blank=True, null=True)),
                ('cp_ins_section', models.IntegerField(blank=True, null=True)),
                ('cp_cor_section', models.IntegerField(blank=True, null=True)),
                ('short_5d_mean_section', models.FloatField(blank=True, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relative_calc', to='stockapi.Ticker')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('absolute_score', models.FloatField(blank=True, null=True)),
                ('relative_score', models.FloatField(blank=True, null=True)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('score_rank', models.IntegerField(blank=True, null=True)),
                ('rank_change', models.IntegerField(blank=True, null=True)),
                ('score_change', models.FloatField(blank=True, null=True)),
                ('lead_agent', models.CharField(blank=True, max_length=20, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_data', to='stockapi.Ticker')),
            ],
        ),
    ]
