# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defacto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefactoReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=6)),
                ('ind_tv', models.FloatField(blank=True, null=True)),
                ('for_tv', models.FloatField(blank=True, null=True)),
                ('ins_tv', models.FloatField(blank=True, null=True)),
                ('cor_tv', models.FloatField(blank=True, null=True)),
                ('ind_coef', models.FloatField(blank=True, null=True)),
                ('for_coef', models.FloatField(blank=True, null=True)),
                ('ins_coef', models.FloatField(blank=True, null=True)),
                ('cor_coef', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='DefacoTicker',
            new_name='DefactoTicker',
        ),
        migrations.AddField(
            model_name='defactoreg',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defaco_reg', to='defacto.DefactoTicker'),
        ),
    ]
