# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0002_kosdaqshort_kospishort'),
        ('defacto', '0002_auto_20180326_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelativeCalc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=6)),
                ('cp_vol', models.FloatField(blank=True, null=True)),
                ('cp_vol_section', models.IntegerField(blank=True, null=True)),
                ('ins_tp_diff', models.FloatField(blank=True)),
                ('for_tp_diff', models.FloatField(blank=True)),
                ('ins_price_inc', models.FloatField(blank=True)),
                ('for_price_inc', models.FloatField(blank=True)),
                ('cp_ind', models.FloatField(blank=True, null=True)),
                ('cp_for', models.FloatField(blank=True, null=True)),
                ('cp_ins', models.FloatField(blank=True, null=True)),
                ('cp_cor', models.FloatField(blank=True, null=True)),
                ('cp_ind_section', models.IntegerField(blank=True, null=True)),
                ('cp_for_section', models.IntegerField(blank=True, null=True)),
                ('cp_ins_section', models.IntegerField(blank=True, null=True)),
                ('cp_cor_section', models.IntegerField(blank=True, null=True)),
                ('short_5d_mean_section', models.FloatField(blank=True, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relative_calc', to='stockapi.Ticker')),
            ],
        ),
        migrations.AddField(
            model_name='agentcalcdata',
            name='lead_agent',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agentcalcdata',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_calc_data', to='stockapi.Ticker'),
        ),
        migrations.AlterField(
            model_name='agentdata',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_data', to='stockapi.Ticker'),
        ),
        migrations.AlterField(
            model_name='defactoreg',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defacto_reg', to='stockapi.Ticker'),
        ),
        migrations.AlterField(
            model_name='rankdata',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_data', to='stockapi.Ticker'),
        ),
        migrations.AlterField(
            model_name='scoredata',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_data', to='stockapi.Ticker'),
        ),
        migrations.DeleteModel(
            name='DefactoTicker',
        ),
    ]
